### ISSUE TITLE
Scaffolding: Brace expansion error

### ISSUE THREAD

**Issue by diessica** [vitorbritto/gruntify#1]
Make uses **sh**, which doesn't support brace expansion, thereby it couldn't work. The makefile must be **bash**, and it will work, I guess. :)

```
SHELL := /bin/bash
```

Another fix could be calling `bash` using the flag `-c` during the `mkdir` with brace expansion.
## 

During the scaffolding process of a new project [`make new`]...

> makefile

```
APP    = app/{scripts/{modules,requires},styles,images/icons,fonts,views,spec/{helpers,modules}}
PUBLIC = public/{scripts,styles,images/icons,fonts}

[...]

    @mkdir -p $(APP)
    @mkdir -p $(PUBLIC)
```

It's creating exactly the following folders:
`app/{scripts/{modules,requires},styles,images/icons,fonts,views,spec/{helpers,modules}}`
(**{modules,requires}** inside **scripts**, **styles** inside **{module,requires}** folder and so forth...)

The same with **public/**:
`public/{scripts,styles,images/icons,fonts}`
## 

Thus, the output reports an error during the scaffolding process:

``` sh
 → Scaffolding
touch: cannot touch ‘app/scripts/main.js’: No such file or directory
make: *** [init_new] Error 1
```

(on **Linux Mint 16 Petra**)

**Comment by diessica** [comment]
This must be enough:

```
@bash -c "mkdir -p $(APP)"
@bash -c "mkdir -p $(PUBLIC)"
```

**Comment by vitorbritto** [comment]
Updating... Thx @diessica! =]
