### ISSUE TITLE
Caminho do path

### ISSUE THREAD

**Issue by dancasttro** [vitorbritto/gruntify#3]
Ola Vitor. No arquivo grunt.conf.js, linha 34 a palavra scripts esta errada esta assim "modules: 'app/scritps/modules'"

**Comment by vitorbritto** [comment]
Opa! Farei a correção. Obrigado @dancasttro! :neckbeard:

**Comment by vitorbritto** [comment]
Correção feita @dancasttro! Obrigado! =]
